#!/bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
if [[ -z "${BashLib}" ]]; then
  printf 'BashLib environment variable is not set\n' >&2
  exit 1
fi
# shellcheck source=/dev/null
# shellcheck disable=SC2154
source "${BashLib}/string.sh"
source "${BashLib}/runner.sh"

runner string::to_upper 'bash'
runner string::to_upper 'Bash'
runner string::to_upper 'BASH'

runner string::to_lower 'bash'
runner string::to_lower 'Bash'
runner string::to_lower 'BASH'
