#!/bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
source "${BashLib}/string/pad"
source "${BashLib}/runner"


runner string_pad_left  10 - padleft
runner string_pad_right 10 - padright
runner string_pad_outer 10 - padouter
runner string_pad_inner 10 - pad inner

