#!/bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
if [[ -z "${BashLib}" ]]; then
  printf 'BashLib environment variable is not set\n' >&2
  exit 1
fi
# shellcheck source=/dev/null
# shellcheck disable=SC2154
source "${BashLib}/string/pad.sh"
source "${BashLib}/runner.sh"

runner string::pad_left 10 - padleft
runner string::pad_right 10 - padright
runner string::pad_outer 10 - padouter
runner string::pad_inner 10 - pad inner