#!/bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
if [[ -z "${BashLib}" ]]; then
  echo 'BashLib environment variable is not set' >&2
  exit 1
fi
# shellcheck source=/dev/null
# shellcheck disable=SC2154
source "${BashLib}/string/repeat.sh"
source "${BashLib}/runner.sh"

runner repeat 2 'Bash'
runner repeat 2 'Bash' 'Separator'