#!/bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
source "${BashLib}/string/repeat"
source "${BashLib}/runner"


runner repeat 2 'Bash'
runner repeat 2 'Bash' 'Separator'

