#!/bin/bash
# -*- coding: utf-8 -*-

export BashLib="${PWD}/src"
# shellcheck source=/dev/null
source "${BashLib}/logging.sh"

usage()
{
    cat <<EOF | sed 's/^    //'
    ${0}: Command [Arguments]

        Commands:
            backup-project      No arguments
            new-file-template   No arguments
            sanitize            No arguments
            set-executable      No arguments
            test-runner         No arguments
EOF
}


new-file-template()
{
    cat <<'EOF'
#!/bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
if [[ -z "${BashLib}" ]]; then
    printf  'BashLib environment variable is not set' >&2
    exit 1
fi
# shellcheck disable=SC2154
# shellcheck source=/dev/null
source "${BashLib}/testing.sh"
source "${BashLib}/utility.sh"
EOF
}


Action="$1"
shift

case "${Action}" in
    backup-project)
        if (( "$#" > 0 )); then
            echo_err "unexpected arguments detected: ${Action} $*"
            exit 1
        fi

        find . -type f  -not -name '*.gz' \
            | xargs tar --force-local -pcvzf "project-$(date -Is).tar.gz"
        ;;

    new-file-template)
        new-file-template
        ;;

    sanitize)
        if (( "$#" > 0 )); then
            echo_err "unexpected arguments detected: ${Action} $*"
            exit 1
        fi

        grep  -lr bin/bash \
            | sort \
            | grep -vE '.*swp$' \
            | xargs shellcheck \
        ;;

    set-executable)
        if (( "$#" > 0 )); then
            echo_err "unexpected arguments detected: ${Action} $*"
            exit 1
        fi

        find                  \
            tests             \
            examples          \
            -type f           \
            -not -name '*swp' \
            -exec chmod 754 {} \;

        find                  \
            src               \
            -type f           \
            -not -name '*swp' \
            -exec chmod ugo-x {} \;
        ;;

    test-runner)
        if (( "$#" > 0 )); then
            echo_err "unexpected arguments detected: ${Action} $*"
            exit 1
        fi

        find ./tests -type f -executable -exec {} \;
        ;;

    help)
        usage
        ;;

    *)
        usage
        exit 2
        ;;
esac

exit
