#!/bin/bash
# -*- coding: utf-8 -*-

find                  \
    src               \
    tests             \
    examples          \
    -type f           \
    -name '*.sh'      \
    -exec chmod 754 {} \;

