#! /bin/bash
# -*- coding: utf-8 -*-

# shellcheck source=/dev/null
# shellcheck disable=SC2154
if [[ -z "${BashLib}" ]]; then
  printf 'BashLib environment variable is not set\n' >&2
  exit 1
fi
# shellcheck source=/dev/null
# shellcheck disable=SC2154
source "${BashLib}/testing.sh"
source "${BashLib}/string.sh"

# Section

testing::test_string_value \
  'A' \
  "$(string::ucase 'a')" \
  'string::ucase: single lowercase character convert to corresponding uppercase character'

testing::test_string_value \
  'AB' \
  "$(string::ucase 'ab')" \
  'string::ucase: two lowercase characters convert to corresponding uppercase characters'

testing::test_string_value \
  'A' \
  "$(string::ucase 'A')" \
  'string::ucase: single uppercase character remains uppercase'

testing::test_string_value \
  'AB' \
  "$(string::ucase 'AB')" \
  'string::ucase: two uppercase characters remain uppercase'

string::ucase 'AB' >/dev/null
rv=$?
testing::test_numeric_value \
  0 \
  $rv \
  'string::ucase: successful operation yields return value 0'

string::ucase >/dev/null
rv=$?
testing::test_numeric_value \
  1 \
  $rv \
  'string::ucase: too few parameters yields return value 1'

string::ucase 'a' 'b' >/dev/null
rv=$?
testing::test_numeric_value \
  1 \
  $rv \
  'string::ucase: too many parameters yields return value 1'

testing::test_string_value \
  'BASH UPPERCASE' \
  "$(string::ucase 'Bash Uppercase')" \
  'string::ucase: mixture of uppercase and lowercase characters are converted to uppercase'

testing::test_string_value \
  ' !"#$%&'"'"'()*+,-./0123456789:;<=>?@[\]^_`{|}~' \
  "$(string::ucase ' !"#$%&'"'"'()*+,-./0123456789:;<=>?@[\]^_`{|}~')" \
  'string::ucase: numbers and symbols remain unaffected'

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  testing::test_summary

  if ((TestCountFail != 0)); then
    testing::list_failed_tests
  fi
fi

# Section

testing::test_string_value \
  'a' \
  "$(string::lcase 'A')" \
  'string::lcase: single uppercase character convert to corresponding lowercase character'

testing::test_string_value \
  'ab' \
  "$(string::lcase 'AB')" \
  'string::lcase: two uppercase characters convert to corresponding lowercase characters'

testing::test_string_value \
  'a' \
  "$(string::lcase 'a')" \
  'string::lcase: single lowercase character remains lowercase'

testing::test_string_value \
  'ab' \
  "$(string::lcase 'ab')" \
  'string::lcase: two lowercase characters remain lowercase'

string::lcase 'AB' >/dev/null
rv=$?
testing::test_numeric_value \
  0 \
  $rv \
  'string::lcase: successful operation yields return value 0'

string::lcase >/dev/null
rv=$?
testing::test_numeric_value \
  1 \
  $rv \
  'string::lcase: too few parameters yields return value 1'

string::lcase 'a' 'b' >/dev/null
rv=$?
testing::test_numeric_value \
  1 \
  $rv \
  'string::lcase: too many parameters yields return value 1'

testing::test_string_value \
  'bash uppercase' \
  "$(string::lcase 'Bash Uppercase')" \
  'string::lcase: mixture of lowercase and uppercase characters are converted to lowercase'

testing::test_string_value \
  ' !"#$%&'"'"'()*+,-./0123456789:;<=>?@[\]^_`{|}~' \
  "$(string::lcase ' !"#$%&'"'"'()*+,-./0123456789:;<=>?@[\]^_`{|}~')" \
  'string::lcase: numbers and symbols remain unaffected'

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  testing::test_summary

  if ((TestCountFail != 0)); then
    testing::list_failed_tests
  fi
fi

# Todo:
# Test input strings work
